### PR TITLE
tutorial notebook renaming rearranging

### PR DESCRIPTION
**Pull request by marcolincs**
### What are the issues this pull addresses (issue numbers / links)?
- Simplifying tutorial notebooks naming/organization based on user feedback.
- Matching documentation folders.

### CODE REVIEW

**Review by JeremyDrysdale-ibm — DISMISSED** [review]

**Comment by priti-ashvin-shah-ibm** [comment]
As part of the pr, it would be helpful to get a list of notebooks that have removed from the tutorial directory.

**Review by dwang429 — APPROVED** [review]
Looks good!

**Review by JeremyDrysdale-ibm — APPROVED** [review]

**Review by dwang429 — DISMISSED** [review]

**Review by ThomasGM4 — DISMISSED** [review]

**Review by JeremyDrysdale-ibm — DISMISSED** [review]

**Review by dwang429 — APPROVED** [review]

**Comment by zlatko-minev** [comment]
Just finishing chatting with @marcolincs  @dwang429  @priti-ashvin-shah-ibm  all good to me after this

**Review by zlatko-minev — DISMISSED** [review]
after push

**Review by JeremyDrysdale-ibm — APPROVED** [review]

**Comment by zlatko-minev** [comment]
This looks great! One final thing we can do in this or a next PR is to add links to the tutorial videos, so we can cross-reference the two

**Pull request merged**
