### PR TITLE
Fix for issue Qiskit#747 (Deprecated code in tutorial)

### PR DESCRIPTION
**Pull request by koloneltedi**
### What are the issues this pull addresses (issue numbers / links)?
The deprecated code in a tutorial, as indicated by issue Qiskit#747

### Did you add tests to cover your changes (yes/no)?
No

### Did you update the documentation accordingly (yes/no)?
Yes (the tutorials)

### Did you read the CONTRIBUTING document (yes/no)?
Yes

### Summary
Replaced deprecated code in tutorial 2.22 by similar code from tutorial 4.01

### Details and comments
Replaced block [11] until [17] from tutorial 2.22 by [7] until [14] from tutorial 4.01. Both the docs\tut folder and tutorials\ folder is updates.

The newly calculated LOM values are slightly different then previously in the tutorial (don't know the exact reason, perhaps the deprecated approach had slightly different internal settings, or another ansys version).

Also: This is my first pull-request here, so let me know if I should do things differently! I'm for example not sure where this CHANGELOG is I should update (or if it is even needed for a tutorial update)

### CODE REVIEW

**Comment by koloneltedi** [comment]
The link to the CLA doesn't seem to work. I'll give it another shot tomorrow.

**Comment by priti-ashvin-shah-ibm** [comment]
> [CLA assistant check](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=754) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=754) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-metal?pullRequest=754) it.

There was an issue with CLA, could you please sign it again?

**Comment by koloneltedi** [comment]
Yes, signed it again. Hope it works

**Review by ThomasGM4 — APPROVED** [review]
Looks good!

**Pull request merged**
