### PR TITLE
reduced youtube logo size

### PR DESCRIPTION
**Pull request by JeremyDrysdale-ibm**
### What are the issues this pull addresses (issue numbers / links)?
None

### Did you add tests to cover your changes (yes/no)?
No

### Did you update the documentation accordingly (yes/no)?
Yes

### Did you read the CONTRIBUTING document (yes/no)?
Yes

### Summary
The youtube logo's were very large for the page.  I reduced them to 60% of the original size.

### CODE REVIEW

**Review by marcolincs — COMMENTED** [review]
Would it make sense to change the text to prevent the second line wrap around? Here two screenshots, first with current text  and second with a possible text change. Also wondering, if we go for the shorter text, if it would be better making the banner even smaller and fit under the text 30->22 (but also 21 works)? (third image)
image
image
image

**Comment by JeremyDrysdale-ibm** [comment]
We can change the text to "Click for Video Tutorials", it's a bit cleaner.  Though, I do not have any text wrap around on my end with the current PR
.
image

**Comment by zlatko-minev** [comment]
Nice, I think a little bit smaller is good. We could add some space, if it allows HTML commands maybe have a couple of points between the icon and the tax just saw that they're not running up against each other.￼

**Comment by zlatko-minev** [comment]
Nice :)

**Review by marcolincs — APPROVED** [review]

**Pull request merged**
