### PR TITLE
Generalizing LaunchPad WB

### PR DESCRIPTION
**Pull request by fgnyilmaz**
### What are the issues this pull addresses (issue numbers / links)?
Generalizing LauncPadWB

### Did you add tests to cover your changes (yes/no)?
Yes
### Did you update the documentation accordingly (yes/no)?
Yes
### Did you read the CONTRIBUTING document (yes/no)?
Yes

### CODE REVIEW

**Comment by marcolincs** [comment]
I went ahead and modified the variable names and defaults to align to the original ones. This way the user will get the benefit of this PR without disruption.
Note: To obtain the dimensions originally suggested by Figet, the following options have to be used:
#         pad_width='300um',
#         pad_gap='150um',
#         pad_height='300um',
#         neck_height='200um',
note that I changed the pad_gap math to provide the singel-side gap width number (original proposal required sum of both sides, which was inconsistent with the transmission line)

What is left to do before we can approve:
- [ ] restore the lead_length math, which was removed in the proposed PR (variable name was reused for transmission line width). Then test all the notebooks for equivalency.

**Review by marcolincs — APPROVED** [review]
I applied a few changes. We should be good now.

**Comment by ThomasGM4** [comment]
Just wanting to check how it impacts the designs from some notebooks.

**Review by ThomasGM4 — APPROVED** [review]
Looks good. Might be some slight fluctuations to the resulting shape if users already have it as part of their notebook, but nothing extreme.

**Pull request merged**
