### PR TITLE
Updates to Interdigitated Transmon Qcomponent

### PR DESCRIPTION
**Pull request by nalanzil**
minor updates to qcomponent and tutorial notebooks to make this design compatible with LOM/EPR/Z analysis

### What are the issues this pull addresses (issue numbers / links)?

Minor qcomponent update, no issue associated. 

### Did you add tests to cover your changes (yes/no)?

Yes, tutorial notebook. 

### Did you update the documentation accordingly (yes/no)?

Yes, updated tutorial notebook. Other documentation exists and is unchanged. 

### Did you read the CONTRIBUTING document (yes/no)?

Yes

### Summary

Minor updates to interdigitated transmon qcomponent. 

### Details and comments

Minor modifications to make compatible with EPR/LOM/Z/eigenmode analysis. Minor updates to tutorial notebook(s) as well.

### CODE REVIEW

**Review by ThomasGM4 — APPROVED** [review]
Looks good

**Review by marcolincs — DISMISSED** [review]
LGTM

although the right way to look at options should be `<class>.get_template_options(design)`, and not `<class>.default_options`. @nalanzil , would you be able to update that in the tut documentation?

This also need to be synched one last time with main, before merge

**Comment by nalanzil** [comment]
@marcolincs updated as requested

**Comment by zlatko-minev** [comment]
Ready to merge?

**Review by marcolincs — APPROVED** [review]

**Pull request merged**
