### PR TITLE
Qutip has to get a fix so we can not use the latest version of numpy.…

### PR DESCRIPTION
**Pull request by priti-ashvin-shah-ibm**
… When fixed, we can remove the limit.

### What are the issues this pull addresses (issue numbers / links)?
Qutip has an issue.  https://github.com/qutip/qutip/pull/1752 is the pull request that will help.  After this is available, we can remove the limit on numpy.

### CODE REVIEW

**Comment by priti-ashvin-shah-ibm** [comment]
Information from @mtreinish!  Thank you for the information.

 There was a configuration format change in numpy made in their most recent release 1.22 (which they decided to release on Dec 31 and that happened to break how qutip was parsing the numpy config.

**Comment by priti-ashvin-shah-ibm** [comment]
I don't need all of you to approve the pull request.  Just wanted you to know this is the fix.  As a sanity check, could one you use Metal with qutip and confirm all is behaving as desired?  

In reflection, fixing this in tox wasn't logical since qutip is used in more than just testing.

**Comment by priti-ashvin-shah-ibm** [comment]
When this is merged, issue #752 can be closed and branch can be deleted.

**Comment by ThomasGM4** [comment]
Should work fine, but couldn't finish testing due to EPR bug I ran into (though the two should be entirely unrelated)

**Review by ThomasGM4 — APPROVED** [review]

**Pull request merged**
