### PR TITLE
install CLtools for macos in README

### PR DESCRIPTION
**Pull request by grace-harper-ibm**
### What are the issues this pull addresses (issue numbers / links)?

#435

### Did you add tests to cover your changes (yes/no)?
no
### Did you update the documentation accordingly (yes/no)?
yes
### Did you read the CONTRIBUTING document (yes/no)?
yes
### Summary
Certain users saw PyQode crashing because they were missing Command Line tools

### CODE REVIEW

**Comment by marcolincs** [comment]
@JeremyDrysdale-ibm , should we have this in the README or in the FAQ? I am a little confused as to where are we going to put the bug solutions going forward. Especially those associated with the "install" process.

Personally, I am thinking we could structure the FAQ to host everything, so not just this PR but all other information stuff could be moved, while in the README we can have instead a link to the FAQ page, installation section (now we can do it since the docs are public). What do you think?

**Comment by JeremyDrysdale-ibm** [comment]
The FAQ already has a section on `Setting up the environment`.  In my mind this, and other environment setup FAQ's should live there (not the readme).  We can split the section up further as needed as we expand our FAQ's.

**Comment by marcolincs** [comment]
Ok, then @grace-harper-ibm, can you move this to the FAQ page instead of the README?

**Comment by grace-harper-ibm** [comment]
will do

**Review by marcolincs — APPROVED** [review]

**Review by JeremyDrysdale-ibm — APPROVED** [review]
LGTM

**Pull request merged**
