### PR TITLE
307 q library filtering fix

### PR DESCRIPTION
**Pull request by Shark-y**
### What are the issues this pull addresses (issue numbers / links)?
https://github.com/Qiskit/qiskit-metal/issues/307

### Did you add tests to cover your changes (yes/no)?
UI fix. Tested in Windows 10.

### Did you update the documentation accordingly (yes/no)?
UI fix. No documentation available.
### Did you read the CONTRIBUTING document (yes/no)?
yes
### Summary
Added a filter to the QLibrary tree view. A fix for https://github.com/Qiskit/qiskit-metal/issues/307

### Details and comments
Added a filter to the QLibrary tree view. This one was very difficult :( Note: It filters by file name

image

### CODE REVIEW

**Comment by priti-ashvin-shah-ibm** [comment]
Thank you so much for contributing code. 

I would say a good notebook to test with is : https://github.com/Qiskit/qiskit-metal/blob/main/tutorials/Appendix%20A%20Full%20design%20flow%20examples/Qiskit_Metal_IMS2022_Notebook.ipynb

For your code, execute the cells prior to Simulation and Analysis and look at GUI.  You will get a large set of components  added to design that you can use for testing. Using this notebook, if you look at the couplers section and type Tee under library, the expected behavior will not happen.  I am sure you are close to the  solution.  


image

**Comment by Shark-y** [comment]
Made an update to address the last comment & tested in win 10. Let me know what u think. Thanks

**Comment by Shark-y** [comment]
@priti-ashvin-shah-ibm Good morning,
What are the desired fixes needed to move Metal from the Alpha stage into the beta? Would love to see this software advance. Thanks

**Comment by priti-ashvin-shah-ibm** [comment]
@Shark-y , please work with @zlatko-minev to get to a common goal.

**Comment by Shark-y** [comment]
@zlatko-minev Hi yes. I'll ask on slack. Thanks

**Comment by Shark-y** [comment]
@zlatko-minev Hi, posted in the slack channel about that but no takers so far. Is there a specific bug you want me to fix? I am a grad student looking for a thesis topic & would like to ask if there is any research idea out there for a phd thesis using metal? Thanks

**Pull request merged**
