### PR TITLE
Implemented S21 fitting methodolgy

### PR DESCRIPTION
**Pull request by SamarthH**
### What are the issues this pull addresses (issue numbers / links)?
This pull requests implements a fitting method to fit S21 extracted from the simulations using the phi-RM method as described by Gao et al and Khalil et al. This is a part of the roadmap as described in Issue #584 

### Did you add tests to cover your changes (yes/no)?
no
### Did you update the documentation accordingly (yes/no)?
no
### Did you read the CONTRIBUTING document (yes/no)?
yes

### CODE REVIEW

**Comment by ThomasGM4** [comment]
This looks really cool! Could you write up a quick tutorial notebook to pair with it? Basically just showing a user how to implement it with an example?

**Comment by SamarthH** [comment]
@ThomasGM4 Hope this works

**Comment by zlatko-minev** [comment]
I'm good if Thomas is good with it ;)

**Review by ThomasGM4 — APPROVED** [review]
Looks good.

Notebook has a bit of cleaning up it could use, like;

`# Define for renderer
eig_qres = EPRanalysis(design, "hfss")
#hfss = design.renderers.hfss
hfss = eig_qres.sim.renderer
q3d = design.renderers.q3d`

But nothing to worry about for now (we need to do a long over do cleanup of all the notebooks).

**Comment by zlatko-minev** [comment]
Just wanted to add again, very cool!

**Pull request merged**
