### PR TITLE
Fix for layout of the GDS/Q3D export window in the gui

### PR DESCRIPTION
**Pull request by Shark-y**
Issue #549
https://github.com/Qiskit/qiskit-metal/issues/549

The scaling for the GDS/Q3D/HFSS dialogs should be fixed now.

### What are the issues this pull addresses (issue numbers / links)?
Issue 549: Small bug in layout of the GDS/Q3D export window in the gui
https://github.com/Qiskit/qiskit-metal/issues/549

### Did you add tests to cover your changes (yes/no)?
No. These are UI layout changes that must be tested manually by scaling the GDS/Q3D & HFSS render dialogs.
There are no python updates. Just QT UI XML

### Did you update the documentation accordingly (yes/no)?
No. I did not find documentation for QT UI XML updates.

### Did you read the CONTRIBUTING document (yes/no)?
yes
### Summary
Updates the QT XML UI for the GDS/Q3D & HFSS render dialogs.

### Details and comments
This is my first attempt at fixing bugs in Qiskit Metal. Please review & let me know if you like them. I made simple updates to the QT XML to auto scale the GDS/Q3D & HFSS render dialogs.

Thank you for your wonderful software.

### CODE REVIEW

**Comment by Shark-y** [comment]
Wrapped the widgets in a GridLayout using the QT designer, so they auto scale at any resolution. The dialog size is left the same. Here are some screen shots at multiple sizes

image
image
# HFSS
image
# Q3D
image

**Comment by Shark-y** [comment]
Good Morning,
A fix for https://github.com/Qiskit/qiskit-metal/issues/45

I should have created a new branch from my last pull request :(

Anyway, the QComponents table now has a QSortFilterProxyModel as shown in the screen shots, you can now sort the table and filter using the text box.

image
image

**Comment by priti-ashvin-shah-ibm** [comment]
To get linting to pass, save your python files with yapf formatting.

**Comment by Shark-y** [comment]
Good morning. Is there a way to rune the above tests from the dev env? Thanks.

**Comment by priti-ashvin-shah-ibm** [comment]
https://github.com/Qiskit/qiskit-metal/blob/main/.pylintrc

Look at line 17 and 18

If these are autogenerated, the files need to be added here.

**Review by priti-ashvin-shah-ibm — COMMENTED** [review]
I tested this on my mac, without M1 it looked good.  Did you test the re-scaling of GUI window on a windows OS?

**Comment by Shark-y** [comment]
Tested in Windows 10.

**Review by priti-ashvin-shah-ibm — APPROVED** [review]
LGTM - Happy to have more contributors to Qiskit Metal. Thank you for your contribution.

**Review by priti-ashvin-shah-ibm — COMMENTED** [review]
LGTM - Thanks for your contribution.

**Pull request merged**
