### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by bicycle315**

### CODE REVIEW

**Comment by JeremyDrysdale-ibm** [comment]
Jeong Won Kim: Please sign the CLA.

**Review by marcolincs — COMMENTED** [review]
Straightforward,....but need the CLA signed for every ID used. It looks like two IDs were used here with 2 commits. I this the same person using two separate IDs? If yes, we might be ok with squash and merge because the only author will be the author of the PR, which is bicycle315.....but better to have all the IDs sign the CLA.

**Comment by bicycle315** [comment]
> Straightforward,....but need the CLA signed for every ID used. It looks like two IDs were used here with 2 commits. I this the same person using two separate IDs? If yes, we might be ok with squash and merge because the only author will be the author of the PR, which is bicycle315.....but better to have all the IDs sign the CLA.

Yes I used 2 ID by mistake. I left bicycle315 as my account and deleted the other one. The other ID is not working anymore so i think no further sign is possible!

**Review by marcolincs — APPROVED** [review]
Let's see what happens then when I merge.

**Comment by bicycle315** [comment]
Thanks!
 
-----Original Message-----

**Pull request merged**
