### PR TITLE
fixed cancel button

### PR DESCRIPTION
**Pull request by grace-harper-ibm**
### What are the issues this pull addresses (issue numbers / links)?
#519 
### Did you add tests to cover your changes (yes/no)?
no
### Did you update the documentation accordingly (yes/no)?
yes
### Did you read the CONTRIBUTING document (yes/no)?
yes
### Summary

Cancel button on closing window now works

### CODE REVIEW

**Review by JeremyDrysdale-ibm — CHANGES_REQUESTED** [review]
The `cancel` button now indeed works.  However, this fix broke the `No` button.  The `No` button behaves like the cancel button now - it should be restored to the previous (correct) functionality where it closed the window without saving.

The be fully clear:
- `Yes` button should save the design and exit (it does) &#x1F7E2;
- `No` button should exit without saving (fails to exit) &#x1F534;
- `Cancel` button should do nothing, no save and no exit (it does) &#x1F7E2;

**Comment by grace-harper-ibm** [comment]
Sorry, I should've made sure to test the other two. 
It turned out because of the `@slot_catch_error()` on `ok_to_continue` that `ok_to_continue`  hadn't actually been returning anything at all when called. 
I removed `@slot_catch_error()` and checked that exceptions will still get printed in the Jupyter Notebook is they occur during that function.

**Review by priti-ashvin-shah-ibm — DISMISSED** [review]
When I tried save-as and then pressed cancel, I had an error.
image

**Comment by grace-harper-ibm** [comment]
@priti-ashvin-shah-ibm I think that's an unrelated issue to this PR. 
I just checked and I get your errors on the commit right before this PR (11afb730b7942945e0db3a94b8294d06beaa759c) and on `main`

**Comment by JeremyDrysdale-ibm** [comment]
> @priti-ashvin-shah-ibm I think that's an unrelated issue to this PR.
> I just checked and I get your errors on the commit right before this PR ([11afb73](https://github.com/Qiskit/qiskit-metal/commit/11afb730b7942945e0db3a94b8294d06beaa759c)) and on `main`

If that's the case, please open that as a separate bug report.

I will re-review this Tuesday morning.

**Review by JeremyDrysdale-ibm — APPROVED** [review]

**Review by priti-ashvin-shah-ibm — APPROVED** [review]
@grace-harper-ibm , I see the bug report.  LGTM.

**Pull request merged**
