### PR TITLE
Issue 45 q components sort filter

### PR DESCRIPTION
**Pull request by Shark-y**
### What are the issues this pull addresses (issue numbers / links)?
https://github.com/Qiskit/qiskit-metal/issues/45

### Did you add tests to cover your changes (yes/no)?
No. This is a UI bug fix.

### Did you update the documentation accordingly (yes/no)?
No. This is a UI bug fix.

### Did you read the CONTRIBUTING document (yes/no)?
yes
### Summary
The QComponents table now has a QSortFilterProxyModel (see screen shots), you can now sort the table and filter using the text box.

### Details and comments

Good Morning,
A fix for https://github.com/Qiskit/qiskit-metal/issues/45

The QComponents table now has a QSortFilterProxyModel as shown in the screen shots, you can now sort the table and filter using the text box.

image
image

### CODE REVIEW

**Comment by Shark-y** [comment]
Moved this commit from my last PR https://github.com/Qiskit/qiskit-metal/pull/938 to a new one. Sorry for the mistake.

**Comment by priti-ashvin-shah-ibm** [comment]
You can make a draft pull request, which will run the github actions for tests.

**Comment by priti-ashvin-shah-ibm** [comment]
https://github.com/Qiskit/qiskit-metal/blob/main/.pylintrc

Look at line 17 and 18

If these are autogenerated, the files need to be added here.

**Review by priti-ashvin-shah-ibm — COMMENTED** [review]
I tested this on my mac, without M1, and  it looked good. Did you test the sort of Qcomponent table window on a windows OS?

**Comment by Shark-y** [comment]
Hi. Tested in Windows 10.

**Review by priti-ashvin-shah-ibm — APPROVED** [review]
LGTM - Thanks for your contribution.

**Pull request merged**
