### PR TITLE
239 nick

### PR DESCRIPTION
**Pull request by nalanzil**
### What are the issues this pull addresses (issue numbers / links)?

This PR addresses Issue #239  by creating a demo notebook which uses the Hcpb class to study the transmon CPB Hamiltonian. 

### Did you add tests to cover your changes (yes/no)?

Yes, all changes are tested in a demo notebook. 

### Did you update the documentation accordingly (yes/no)?

No

### Did you read the CONTRIBUTING document (yes/no)?

Yes

### Summary

This PR includes one demo notebook, a minor modification to the file transmon_charge_basis.py (in order to normalize the wavefunctions) and the inclusion of a new class in transmon_CPB_analytic.py which calculates the exact solutions. The demo notebook also includes several additional analysis plots, including charge dispersion, energy level deltas, anharmonicity and charge-limited dephasing time.

### Details and comments

See above. This branch can be deleted upon successful merge.

### CODE REVIEW

**Comment by marcolincs** [comment]
@nalanzil , can you please add to the notebook a description as to how to install scqubits? and how to "not" install it? For example, pip install in an existing conda will not work (Thomas and I tried unsuccessfully), maybe some conditions have to be met for that to work? Or maybe conda users need to get conda install? What worked for me was to edit environemnt.yml to include scqubit and create a brand new conda env

**Comment by nalanzil** [comment]
@zlatko-minev can you comment on @marcolincs 's comment above? I actually do not have scqubits installed. Maybe developing that part of the notebook should be listed as a new issue?

**Comment by zlatko-minev** [comment]
Are there intermediate points here in the curve? I guess not, since the curves should look quadratic, but look a bit more linear?
image

**Comment by nalanzil** [comment]
> 
> 
> Are there intermediate points here in the curve? I guess not, since the curves should look quadratic, but look a bit more linear?
> image

Good call. That's actually old code that uses the analytic solution for the plots (and thus only integer values of offset charge.) Just updated the notebook to use the Hcpb class, plots are much smoother now.

image

**Review by JeremyDrysdale-ibm — APPROVED** [review]
LGTM

**Review by zlatko-minev — APPROVED** [review]

**Comment by zlatko-minev** [comment]
Great job, @nalanzil !

**Pull request merged**
