### PR TITLE
Final PR for Issue #733

### PR DESCRIPTION
**Pull request by bopardikarsoham**
@priti-ashvin-shah-ibm. I have fixed the typos in both files and have also run both the notebooks to show it as a tutorial. This is my final PR and you can close PR #746 and #748.

### CODE REVIEW

**Comment by priti-ashvin-shah-ibm** [comment]
@bopardikarsoham , we have has some issues with the CLA bot.  Even though contributor has signed it, we need to ask them to sign again.  Can you please sign the CLA again.

**Comment by bopardikarsoham** [comment]
Ok, I have signed the CLA again

**Comment by priti-ashvin-shah-ibm** [comment]
> 

Per your request, I will close  PR #746 and #748.

**Comment by bopardikarsoham** [comment]
Is the PR ok?

**Comment by priti-ashvin-shah-ibm** [comment]
@bopardikarsoham , I see that we could merge this, however, there are many warnings in the notebooks which would  show in documentation.  Let's wait till the fix for issue #727.  After that fix is merged, the repository will be updated so the warnings will not occur in the notebooks you ran.


https://github.com/Qiskit/qiskit-metal/issues/727

**Comment by bopardikarsoham** [comment]
Ok, no problem @priti-ashvin-shah-ibm

**Comment by priti-ashvin-shah-ibm** [comment]
HI @bopardikarsoham 

The fix to address the warnings for shapely depreciation just merged to main.  We were waiting for this merge before running the books.  

So, now, if you can make a new conda environment from latest commit on main, then run the notebooks, the output of the cells in the notebook shouldn't have the warnings in them.

**Comment by bopardikarsoham** [comment]
Sure @priti-ashvin-shah-ibm

**Comment by priti-ashvin-shah-ibm** [comment]
@bopardikarsoham , since you opened a different pull request, I am closing this pull request.

**Pull request closed without merging**
