### PR TITLE
GDS Renderer gdspy library precision argument passing

### PR DESCRIPTION
**Pull request by bashensen**
### What are the issues this pull addresses (issue numbers / links)?
Issue #611

### CODE REVIEW

**Comment by priti-ashvin-shah-ibm** [comment]
@bashensen , can you please add your changes to the latest commit from main?

**Comment by bashensen** [comment]
Sorry my bad, fetched and merged my forked one now. 

Still no precision argument passed upon creation of the gdspy lib

**Review by JeremyDrysdale-ibm — APPROVED** [review]
LGTM  @priti-ashvin-shah-ibm What are your thoughts?

**Review by priti-ashvin-shah-ibm — APPROVED** [review]
@bashensen , thanks for updating branch.  You were correct, precision argument still needs to be passed. LGTM

**Pull request merged**
