### PR TITLE
Fixed Code Error in Issue #733

### PR DESCRIPTION
**Pull request by bopardikarsoham**
I have set size_x to 9mm as per #733

### CODE REVIEW

**Comment by priti-ashvin-shah-ibm** [comment]
Hi @bopardikarsoham , 
Thank you for helping with Issue #733.  

In the issue, you have finished one part of the request.  Are you interested to complete the part that says, "The notebook in tut directory needs to be run and saved.  ... and
the cell has to be updated here.... "?   

We can not close the issue without doing the second part. 




```
It appears that size_x should be ‘9mm’ in the two notebooks. The notebook in tut directory needs to be run and saved.

https://qiskit.org/documentation/metal/tut/2-From-components-to-chip/2.21-Design-a-4-qubit-full-chip.html#Let%E2%80%99s-design-the-core-of-the-chip

and
the cell has to be updated here.

https://github.com/Qiskit/qiskit-metal/blob/main/tutorials/2%20From%20components%2[…]chip%20design/2.21%20Design%20a%204%20qubit%20full%20chip.ipynb
```

**Comment by bopardikarsoham** [comment]
Yes, you're correct @priti-ashvin-shah-ibm; I'll do the other part as well.

**Comment by bopardikarsoham** [comment]
@priti-ashvin-shah-ibm I have added another PR #748 for the other file.

**Comment by priti-ashvin-shah-ibm** [comment]
Hi @bopardikarsoham , There has been a commit added to Metal.  Can you merge the latest commit into this pull request?  Then I am thinking your pull request will pass CI checks.

**Comment by priti-ashvin-shah-ibm** [comment]
@bopardikarsoham , Can you please merge the latest commit on Metal into this pull request?  I believe the CI will pass then.

**Comment by priti-ashvin-shah-ibm** [comment]
Per request of contributor on Pull request #759, I am closing this pull request.

**Pull request closed without merging**
