### PR TITLE
Fixed Code Error in Issue #733(Additional PR)

### PR DESCRIPTION
**Pull request by bopardikarsoham**
An addition to PR #746 @priti-ashvin-shah-ibm.

### CODE REVIEW

**Comment by priti-ashvin-shah-ibm** [comment]
@bopardikarsoham , For this notebook, did you execute it before generating this PR?

**Comment by bopardikarsoham** [comment]
I am getting an error: **No module named "qiskit_metal"** despite the fact I am running it in the cloned folder itself.

**Comment by priti-ashvin-shah-ibm** [comment]
> I am getting an error: **No module named "qiskit_metal"** despite the fact I am running it in the cloned folder itself.

To run the notebooks, one has to make a conda env based on the directions in link below.  I had assumed you already had one set up.  

https://qiskit.org/documentation/metal/installation.html

**Review by zlatko-minev — APPROVED** [review]

**Comment by zlatko-minev** [comment]
Thanks for the pull. It looks like the code just fixes a simple typo of size_y to size_x. Shouldn't affect anything else

**Comment by bopardikarsoham** [comment]
> @bopardikarsoham , For this notebook, did you execute it before generating this PR?
> 
> The issue had said, "The notebook in tut directory needs to be run ". The purpose of running/executing the cells is that when the notebook is posted in the documentation, other users can see what the expected output would be.

@priti-ashvin-shah-ibm Do you want me to show it as a tutorial? I can do that too.

**Comment by priti-ashvin-shah-ibm** [comment]
> > @bopardikarsoham , For this notebook, did you execute it before generating this PR?
> > The issue had said, "The notebook in tut directory needs to be run ". The purpose of running/executing the cells is that when the notebook is posted in the documentation, other users can see what the expected output would be.
> 
> @priti-ashvin-shah-ibm Do you want me to show it as a tutorial? I can do that too.

@bopardikarsoham , yes , thank you!   The updated notebook would need to be executed with the updated output and the shared in the docs.

**Comment by bopardikarsoham** [comment]
Here is the PR #759 @priti-ashvin-shah-ibm.

**Comment by priti-ashvin-shah-ibm** [comment]
Per request of contributor on Pull request #759, I am closing this pull request.

**Pull request closed without merging**
