### PR TITLE
open_to_ground_v2

### PR DESCRIPTION
**Pull request by fgnyilmaz**
open_to_ground default options were not generalized. width & gap and termination_gap was with some constant numbers so when One change their cpw_width and cpw_gap, open to ground's extra part was not changing accordingly.

What are the issues this pull addresses (issue numbers / links)?
open_to_ground default options were not generalized. width & gap and termination_gap was with some constant numbers so when One change their cpw_width and cpw_gap, open to ground's extra part was not changing accordingly.

Did you add tests to cover your changes (yes/no)?
Yes

Did you update the documentation accordingly (yes/no)?
Yes

Did you read the CONTRIBUTING document (yes/no)?
Yes

Summary
When One want to use different cpw_with and cpw_gap, the extra part (that makes the resonator not grounded) of open to the ground does not change because it was fixed as 10um and 6um, respectively. I changed them to cpw_width and cpw_gap as needed and it works now. Analyses also work.

Details and comments
Just updated some of the default options to have a generalized open to ground library.

### CODE REVIEW

**Comment by priti-ashvin-shah-ibm** [comment]
> [CLA assistant check](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=744) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=744) before we can accept your contribution.**2** out of **4** committers have signed the CLA.✅ fgnyilmaz✅ marcolincs❌ ThomasGM4❌ priti-ashvin-shah-ibmYou have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-metal?pullRequest=744) it.

Hi @ThomasGM4 , there has been an issue with CLA, could you sign it again?

**Review by ThomasGM4 — APPROVED** [review]

**Review by ThomasGM4 — CHANGES_REQUESTED** [review]
Oh, can you put the component into the proper folder?

**Comment by fgnyilmaz** [comment]
> 

will do now :) 

Amazing news :dancers:

**Comment by ThomasGM4** [comment]
Hi @fgnyilmaz, once you move the new component to the appropriate folder (qlibrary\terminations\) we can merge the PR

**Comment by fgnyilmaz** [comment]
> Hi @fgnyilmaz, once you move the new component to the appropriate folder (qlibrary\terminations) we can merge the PR

I moved there but have other errors, I will close this one now. Thank you :)

**Pull request closed without merging**
