### PR TITLE
Fixed a Typo

### PR DESCRIPTION
**Pull request by divshacker**
### What are the issues this pull addresses (issue numbers / links)?
There was a typo in  https://qiskit.org/documentation/metal/workflow.html

### Did you add tests to cover your changes (yes/no)?
No
### Did you update the documentation accordingly (yes/no)?
yes
### Did you read the CONTRIBUTING document (yes/no)?
yes
### Summary
All details can be find in Files changes section

### Details and comments
Please let me know if any editing needed.
Thank You

### CODE REVIEW

**Comment by divshacker** [comment]
Check this out @zlatko-minev

**Review by JeremyDrysdale-ibm — APPROVED** [review]
LGTM
Nice catch @divshacker

**Comment by zlatko-minev** [comment]
> 
> 
> 
> 
> 
> 
> ### What are the issues this pull addresses (issue numbers / links)?
> 
> There was a typo in  https://qiskit.org/documentation/metal/workflow.html
> 
> 
> 
> ### Did you add tests to cover your changes (yes/no)?
> 
> No
> 
> ### Did you update the documentation accordingly (yes/no)?
> 
> yes
> 
> ### Did you read the CONTRIBUTING document (yes/no)?
> 
> yes
> 
> ### Summary
> 
> All details can be find in Files changes section
> 
> 
> 
> 
> 
> ### Details and comments
> 
> Please let me know if any editing needed.
> 
> Thank You
> 
> 
> 
> 



Great catch thanks!

**Comment by zlatko-minev** [comment]
great catch￼! Thanks!

**Pull request merged**
