### PR TITLE
795 conda env  python3 10

### PR DESCRIPTION
**Pull request by priti-ashvin-shah-ibm**
### What are the issues this pull addresses (issue numbers / links)?
#795 is mostly finished, however, we still need to add python 3.10 CI. 

### Did you add tests to cover your changes (yes/no)?
no

### Did you update the documentation accordingly (yes/no)?
Yes

### Did you read the CONTRIBUTING document (yes/no)?
yes

### Summary
pyaedt has dependencies which limit python to 3.9.  So we are holding off on merging this pull request for now.

### CODE REVIEW

**Comment by priti-ashvin-shah-ibm** [comment]
This work was done by @GyeonghunKim  as part of QAMP.

**Comment by priti-ashvin-shah-ibm** [comment]
Regarding Qiskit Metal,   when we are using the latest commit, the conda environment has python 3.10.  When we add the dependencies for pyaedt i.e. PythonNet and PyVista,  then generate a new conda env, the environment is python 3.9.  This makes us believe PythonNet and PyVista have some code which is not python 3.10 compatible.  This is just sharing of information; however, it would be ideal to not limit python version.

**Comment by priti-ashvin-shah-ibm** [comment]
We noticed pyaedt is not part of conda-forge. If we want to use that package, we would need to manually pip install.

**Review by obrienpja — APPROVED** [review]
LGTM, go team!

**Comment by priti-ashvin-shah-ibm** [comment]
@GyeonghunKim  Thank you for all of your help to get the repo to work with python 3.10.

**Review by obrienpja — APPROVED** [review]
LGTM, good job!

**Review by obrienpja — APPROVED** [review]
LGTM, glad we are slimming this down!

**Pull request merged**
