### PR TITLE
Issue #477 sweep drivenmodal

### PR DESCRIPTION
**Pull request by priti-ashvin-shah-ibm**
### What are the issues this pull addresses (issue numbers / links)?
Issue 477 will be closed after this is merged.

### Did you add tests to cover your changes (yes/no)?
no, but added a notebook to Tutorials/6 Anslysis

### Did you update the documentation accordingly (yes/no)?
yes

### Did you read the CONTRIBUTING document (yes/no)?
yes

### Summary
This adds a feature that user can sweep list of options in Metal, and then calculate the sweep in Ansys drivenmodal.

### CODE REVIEW

**Comment by ThomasGM4** [comment]
Tests take a little long given the simulations, will try and get this reviewed by tomorrow.

**Review by JeremyDrysdale-ibm — DISMISSED** [review]
LGTM

**Comment by ThomasGM4** [comment]
- A new frequency sweep is created for each pass (not a huge deal, but best to avoid the re-adding if possible)

Capture

- The freq_ghz should allow float (eg. 7.5)

Capture2

**Comment by ThomasGM4** [comment]
Another potential improvement, having the port names match up (Eg. not simply S11, but S_`LumpPort_cpw_openLeft_end_LumpPort_cpw_openLeft_end`, or S21 -> S_`LumpPort_cpw_openRight_end_LumpPort_cpw_openLeft_end` )

This way the user knows what port is actually pointing to what part of their layout. Although we probably should be simplifying the names of the ports being generated in Ansys too anyhow. (eg. LumpPort_cpw_openLeft_end ->LP_cpw_openLeft_end)

**Comment by priti-ashvin-shah-ibm** [comment]
> Another potential improvement, having the port names match up (Eg. not simply S11, but S_`LumpPort_cpw_openLeft_end_LumpPort_cpw_openLeft_end`, or S21 -> S_`LumpPort_cpw_openRight_end_LumpPort_cpw_openLeft_end` )
> 
> This way the user knows what port is actually pointing to what part of their layout. Although we probably should be simplifying the names of the ports being generated in Ansys too anyhow. (eg. LumpPort_cpw_openLeft_end ->LP_cpw_openLeft_end)

Made a new issue #526 to address this.

**Review by JeremyDrysdale-ibm — APPROVED** [review]
LGTM

**Review by ThomasGM4 — APPROVED** [review]
Looks good on my end

**Pull request merged**
